language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/allocation_event_source
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "allocation_event_source";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./allocation_event_source/manage.py test allocation_event_source
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: allocation_event_source-dev
    qa: allocation_event_source-qa
    prod: allocation_event_source-prod
  on:
    repo: julianpistorius/allocation_event_source
  run:
    - "./allocation_event_source/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true
